### ISSUE TITLE
Actividad 5 Cuadro Comparativo Maribel Santiago Bautista 1°BS

### ISSUE THREAD

**Issue by santiagomary1004** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-santiagomary1004#1]
[Actividad 5 Cuadro Comparativo_Maribel Santiago Bautista.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-santiagomary1004/files/9642209/Actividad.5.Cuadro.Comparativo_Maribel.Santiago.Bautista.pdf)

**Comment by ErikCuevas03** [comment]
18  , cuida la ortografía

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
